### ISSUE TITLE
great work! are there other AT commands ?

### ISSUE THREAD

**Issue by PhotoAtomic** [magcode/sunricher-wifi-mqtt#1]
hello! i've just bought a sunricher controller SR-2818WiN 
i'm implementing my own lighting solution, and your great work saved me a lot of work, thank you!

i was just wondering how you have discovered about the AT+MSLP=off command, and if there are any other already knows.

is this all reverse-engineering or are there some datasheet of some sort somewhere?
thanks again!

**Comment by magcode** [comment]
Glad that you find it helpful
Regarding the at commands... iirc the wifi module is a HF-A11. goggle that and you will find a user manual with at commands

**Comment by PhotoAtomic** [comment]
thanks! for future reference i've found the datasheet here http://www.elecomes.com/goods.php?id=158
and for the operating protocol and the related constant values? reverse engineering or is there another well-known chip inside?

**Comment by magcode** [comment]
right. Just be aware that the SR-2818WiN might run an older version/firmware of the HF-A11 (you can see it somewhere in the web ui of the device)

regarding the control protocol: yes, unfortunately this is hard reverse engineering work

sources: 
* android app
* maybe wireshark
* other projects that have build a controlling interface

**Comment by magcode** [comment]
do you plan to enhance the code or support more devices/features?

**Comment by PhotoAtomic** [comment]
i'm new in the home-automation world, i would like to see what i can achieve, the final goal is to support amazon alexa and allow some light animation.
i've 6 light zone already installed and i'm planning to extend to 9, the app only support 8, i'm quite curious to see if this limitation can be overtaken.

probably i'll port the code to .net core because i'm more proficient in it.

**Comment by magcode** [comment]
OK. IC. Have fun!
