### ISSUE TITLE
Protocol clarification

### ISSUE THREAD

**Issue by dannyyy** [magcode/sunricher-wifi-mqtt#11]
Hi,

I tried to use some of the C# APIs who have credited your project as the initial one. So far, thank you for your great work doing the reverse engineering.

Unfortunately, I guess I'm already struggling with some basic concepts.  Maybe you can help me with these questions from experience:
- Does the receiver (dim actors, transformers) ever send any commands out, e.g. for the sake of the learning process (clicking on the learning key)?  
_My guess is not, only ready to receive and learn_
- Does the remote (Wifi/Lan Bridge, classical remote) ever receive any commands, e.g. for the sake of the pairing process?  
_My guess is not, only sends commands. The receiver has to decide whether the command should be used to switch/dim the light or to learn a new id_
- What is the definition of a zone or room? Is it the same?  
_My guess is, that a zone/room is the same but a different name. Furthermore, a receiver can bind to multiple remote ids. By implication this means, that an id on the remote is one zone/room. Is this right?

The reason for these kinda silly questions is, that independent of the room I use with your library, all lights will either switch on or off. Behaves like a broadcast to all receivers. In the app, I'm able to control with the three different room images, three different lights, because I assigned them accordingly during the learning process.

After that I also started my reverse engineering process by capturing the network traffic from my android phone sent to the bridge and compared these commands against what your library is sending.

To switch on and off one room/zone with your library (all lights are reacting):
```
On:  55 00 00 00 00 00 02 0a 93 9f aa aa
Off: 55 00 00 00 00 00 02 0a 92 9e aa aa
```

To switch on and off one room/zone with the app (only the expected light is reacting):
```
On:  55 77 8c e9 01 01 02 0a 93 a1 aa aa
Off: 55 77 8c e9 01 01 02 0a 92 a0 aa aa
```

Before I invest lot more time doing this, maybe someone can give me some basic understandings. Unfortunately, the official app as well as the original manual is such bad, that I often not know what the app is really doing if I click somewhere. Furthermore, doing the same in different order behaves totally different.

Thank you!
Cheers Danny

**Comment by dannyyy** [comment]
I've closed this issue due to miss-implementation of the fork(s).
I went through your code and you set the _zone_ accordingly. Other implementations only set the bytes 6-8 and omit the necessary room bytes 4-5. After fixing this, also the C# APIs are working as expected.

**Comment by magcode** [comment]
👍

**Comment by Barabba11** [comment]
> 
> 
> Hi,
> 
> I tried to use some of the C# APIs who have credited your project as the initial one. So far, thank you for your great work doing the reverse engineering.
> 
> Unfortunately, I guess I'm already struggling with some basic concepts. Maybe you can help me with these questions from experience:
> 
>     * Does the receiver (dim actors, transformers) ever send any commands out, e.g. for the sake of the learning process (clicking on the learning key)?
>       _My guess is not, only ready to receive and learn_
> 
>     * Does the remote (Wifi/Lan Bridge, classical remote) ever receive any commands, e.g. for the sake of the pairing process?
>       _My guess is not, only sends commands. The receiver has to decide whether the command should be used to switch/dim the light or to learn a new id_
> 
>     * What is the definition of a zone or room? Is it the same?
>       _My guess is, that a zone/room is the same but a different name. Furthermore, a receiver can bind to multiple remote ids. By implication this means, that an id on the remote is one zone/room. Is this right?
> 
> 
> The reason for these kinda silly questions is, that independent of the room I use with your library, all lights will either switch on or off. Behaves like a broadcast to all receivers. In the app, I'm able to control with the three different room images, three different lights, because I assigned them accordingly during the learning process.
> 
> After that I also started my reverse engineering process by capturing the network traffic from my android phone sent to the bridge and compared these commands against what your library is sending.
> 
> To switch on and off one room/zone with your library (all lights are reacting):
> 
> ```
> On:  55 00 00 00 00 00 02 0a 93 9f aa aa
> Off: 55 00 00 00 00 00 02 0a 92 9e aa aa
> ```
> 
> To switch on and off one room/zone with the app (only the expected light is reacting):
> 
> ```
> On:  55 77 8c e9 01 01 02 0a 93 a1 aa aa
> Off: 55 77 8c e9 01 01 02 0a 92 a0 aa aa
> ```
> 
> Before I invest lot more time doing this, maybe someone can give me some basic understandings. Unfortunately, the official app as well as the original manual is such bad, that I often not know what the app is really doing if I click somewhere. Furthermore, doing the same in different order behaves totally different.
> 
> Thank you!
> Cheers Danny

Hi dannyyy the answer is no, the receiver don't have an hardware transmitter, they can just receive. ANd the Wi-Fi bridge is extremely stupid, it clean the IP packet from TCP headers and send RF the string you send. That's why it's extremely important you respect the quantity of messages and the time between each other, if you don't want to see your dimmers got corrupted. Unfortunately this may happen after months and you will not have idea when it happened and why. It's also quite difficult to clean them to factory settings and re use them, there may be also problems with wall buttons, like you can't switch more the lamp on with a short press.
I strongly suggest you to read my experiments here:
https://github.com/magcode/sunricher-wifi-mqtt/issues/8
