### ISSUE TITLE
Sunricher devices with openhab

### ISSUE THREAD

**Issue by gurtjun** [magcode/sunricher-wifi-mqtt#2]
Hi, not sure if this is the best way to contact you. But I read your post on this thread: https://community.openhab.org/t/what-dimmer-switch-for-led-bulbs-uk/30916/23 .

It seems that you were able to add the sunricher devices to openhab? 
I have a setup with the same devices (including wifi bridge) but I cannot manage to connect them to openhab.

Any tips? 

KR,
Gert-jan

**Comment by magcode** [comment]
Hello,

3 steps:

1) install an MQTT broker
2) get MQTT running in Openhab (read docs)
3) get this tool here (sunricher-wifi-mqtt) running
4) create some items in Openhab e.g.
```
Switch switchC1 "ceil1" {mqtt=">[mosquitto:home/led/3/power:command:ON:1],>[mosquitto:home/led/3/power:command:OFF:0]"}
Dimmer dimmerC1 "ceil1" {mqtt=">[mosquitto:home/led/3/brightness:command:*:default]"}
```

This should do the trick
