### ISSUE TITLE
RGB Led control

### ISSUE THREAD

**Issue by mshaposhnikov** [magcode/sunricher-wifi-mqtt#3]
Hi!

I've got  Sunricher RGB led strip and it would be nice to support it (i'd like to integrate to my smart home controller).

Happy to sponsor (to cover expense) some Sunricher RGB device to develop and test

**Comment by magcode** [comment]
Hey, what particular product(s) do you have?

**Comment by mshaposhnikov** [comment]
Hi!

http://www.sunricher.com/high-voltage-led-strip-rf-controller-sr-1009ht.html <http://www.sunricher.com/high-voltage-led-strip-rf-controller-sr-1009ht.html>

+ outdoor 230V IP67 LED strip



-----------------------------



Regards,

Maxim Shaposhnikov, High Performance LTD.

Phones:
UK:		+447798720657
US:		+13055078443
Russia:  +74997044776

**Comment by magcode** [comment]
Hi. I checked this ...

It seems in general compatible with my solution, thus I see a good chance to get this supported/implemented.

I don't have high voltage led strips available so we would have two options:

1) funding of sr-1009ht AND a high voltage LED strip
2) funding of a different device (SR-1009FA) which works with 12v led strips (I have some at home, no need to buy). This option comes with a small risk as it is not the same device as you have. However I'm 95% sure that the Sunricher SR-1009xx devices are all compatible.

timewise I think it is feasible during summer
