### ISSUE TITLE
there is any way to read the brightness percentage?

### ISSUE THREAD

**Issue by Barabba11** [magcode/sunricher-wifi-mqtt#7]
Hi there )
I'm going to test it soon, since I'm using also the dimmer button contacts for dimming I would know if it's possible to read the status, it can be different from the last command from WiFi.. thanks

**Comment by magcode** [comment]
Nope. Thats not possible.

**Comment by Barabba11** [comment]
Good morning! Thank you for kind answer, yes when I went to sleep I also thought about that, the comunication is only unidirectional, the dimmers only receive the signal.
It is possible to overcome that sending a "power off", and then "power on", the dimmer will remember the its last value..
I'll test it soon )
